pipeline {
    agent any
    stages {
        stage('Build'){
            steps {
                sh 'make build'
            }
        }
        stage('Test'){
            steps {
                sh 'make up'
            }
        }
        stage('Clean') {
            steps {
                sh 'make stop'
                sh 'make clean'
            }
        }
    }
}